# Air Law {#airlaw}

## International law conventions agreements and organizations

### International Law

* no international law enforcement
* States required to ratify agreed conventions into national law

THERE WAS MORE CHECK AND EXPAND

### ICAO 

International Civil Aviation Organisation

* created in 194x, established after ratification
* became specialised organisation of United Nations

Organisation of ICAO

* bodies ... air transport, air navigation, ...

Freedomes of the air

* elaborate on the various freedoms

ICAO Annexes

Annex
Subject
1
Personnel Licensing (Getting a license is my Number 1 priority)
2
Rules of the Air (2 Sets of Rules, VFR and IFR)
3
Meteorological Services (3ºC/1000ft DALR or 1deg/100m)
4
Aeronautical Charts (4 Cardinal Points)
5
Dimensional Units (CRP 5)
6
Operation of Aircraft (DC6)
7
Nationality and Registration Marks (The League of Seven Nations)
8
Airworthiness (Looks like a propeller)
9
Facilitation (NEIN in German – Immigration)
10
Aeronautical Communications (100 for the Operator)
11
Air Traffic Control Services (1 to 1 Personal Services)
12
Search & Rescue (The one before Accident Investigation)
13
Accident Investigation (Unlucky for some)
14
Aerodromes (14 Aerodromes around Heathrow)
15
Aeronautical Information Services (Looks like IS)
16
Environmental Protection (16 Age of Consent, use protection)
17
Security (17ft security fence required)
18
Dangerous Goods (At 18 you can drink but it’s DANGEROUS to drive) 

### EASA

European Aviation Safety Agency

### IATA

International Air Transport Associated

### EUROCONTROL

European Organisation for the Safety of Air Navigation


## Flight Crew Licensing

"please refer to part FCL" :)

## Rules of the Air

### Terms and Definitions

a good set / mix of definitions ranging from IFR/VFR IMC/VMC, services/units, controlled flight, aerodrome terms, airspace classes.

IDEA: REWORK AND DEVELOP SUBSECTION TO ALIGN/DIFFERENTIATE BETTER.

Note: Automatic dependent surveillance (ADS) is "emphasised" with introducing ADS agreement and contract at the beginning of the list of defintions.

### Rules of the Air

Applicability
The rules of the air shall apply to aircraft bearing the nationality and registration marks  of  a  Contracting  State,  wherever  they  may  be,  to  the  extent  that  they  do  not  conflict  with  the  rules  published  by  the  State  having  jurisdiction  over  the  territory overflown.

over high seas: (unless notified differently) appropriate ATS authority = as designated by the State assuming to provide services under a regional air navigation agreement.

Compliance with the rules of the air    
The  operation  of  an  aircraft  either  in  flight  or  on  the  movement  area  of  an  aerodrome shall be in compliance with the general rules and, in addition, when in flight, either with:a) the visual flight rules or b) the instrument flight rules

Responsibility of pilot-in-command    
The  pilot-in-command  of  an  aircraft  shall,  whether  manipulating  the  controls  or not, be responsible for the operation of the aircraft in accordance with the rules of the  air,      
except   
that  the  pilot-in-command  may  depart  from  these  rules  in  circumstances that render such departure absolutely necessary in the interests of safety.

Preflight action for flights away from vicinity of aerodrome and all IFR
- current weather reports and forecasts
- fuel requirements    
- alternate course of action, if flight cannot be completed as planned.

Authority     
The pilot-in-command of an aircraft shall have final authority as to the disposition of the aircraft while in command.

No  person  whose  function  is  critical  to  the  safety  of  aviation  (safety-sensitive personnel)   shall   undertake   that   function   while   under   the   influence   of   any   psychoactive substance, by reason of which human performance is impaired.    
No such person shall engage in any kind of problematic use of substances.


#### General Rules

AVODING COLLISIONS

* proximity - no operations in such proximity as to create collision hazards
* right-of-way - 
    + right of way a/c to maintain heading and speed unless PIC collision avoidance
    + a/c giving way: no passing over, under, in front, unless well clear and considering effect of wake turbulences
    + head-on: both aircraft alter heading to the right
    + converging (same level) a/c having the other on their right to give way ("Rechts-vor-Links") with the exception
       + a) power-driven heavier-than-air aircraft shall give way to airships, gliders and balloons;
       + b) airships shall give way to gliders and balloons;
       + c) gliders shall give way to balloons;
       + d)  power-driven  aircraft  shall  give  way  to  aircraft  which  are  seen  to  be  towing other aircraft or objects.
    + overtaking: from behind within 70deg / no view of position lights at night, to the right and stay clear (climb, descent, same level) until entirely past and clear (including changes by the a/c overtaken)
    + a/c in flight or on ground/water give way to a/c landing or in final stages of approach
       + in case of simultaneous approaches: higher aircraft to give way to lower a/c
       + power-driven a/c give way to gliders
    + emergency landing
    + taxiing aircraft give way to a/c taking off or about to take off
    + surface movement: head on = stop, as appropriate of both to the right, converging: a/c from right has right of way/other give way, overtaking: a/c to be overtake has right of way, other to stay clear
    
FOMRATION FLYING

* 1km  laterally  and  longitudinally  and  30m  vertically  from  the  flight  leader
* no formation flight except by "pre-arrangement" among PICs

TAXIING FLIGHTS

An  aircraft  taxiing  on  the  manoeurvring  area  shall  stop  and  hold  at  all  runway-holding positions unless otherwise authorized by the aerodrome control tower.    
An aircraft taxiing on the manoeuvring area shall stop and hold at all lighted stop bars and may proceed further when the lights are switched off

LIGTHS 

* in flight from sunset to sunrise or any other period prescribed by appropriate authority
  + anti-collision lights intended to attract attention of other aircraft
  + navigation lights indicated to signal the relative path of the aircraft
  + no other lights if they are likely to be mistaken
* moving aircraft on movement area shall dispaly navigation lights signalling relative path & no other lights if to be mistaken
* unless stationary and adequately illuminated aircraft shall display lights that to indicate the extremeties\

many clauses: basically operate anti-collision lights (attracting attention) at all times (outside sunset to sunrise) on movement area or in flight

Lights can be switched off or lowered in intensity by pilot if
* adversely affect the satisfactory performance of duties; or
* subject an outside observer to harmful dazzle.


MINIMUM HEIGHTS

Except when necessary for take-off or landing, or except by permission from the appropriate  authority,  aircraft  shall  not  be  flown  over  the  congested  areas  of  cities,  towns  or  settlements  or  over  an  open-air  assembly  of  persons,  unless  at  such a height as will permit, in the event of an emergency arising, a landing to be made without undue hazard to persons or property on the surface.

VFR
* over the congested areas of cities, towns or settlements or over an open-air assembly, NOT less than 300 m (1000 ft) within a radius of 600 m of the highest obstable;
* elsewhere other: NOT less than 150 m (500 ft) over ground/water

IFR
* except for take-off, landing, or specifically authorised, an IFR flight shall be flown not below the minimum flight altitude established, or - if such miniumum is not established -
* over high terrain or in mountainous areas, at a level which is at least 600 m  (2.000  ft)  above  the  highest  obstacle  located  within  8  km  of  the  estimated position of the aircraft
* Elsewhere than  as  specified  above,  at  a  level  which  is  at  least  300  m (1.000 ft) above the highest obstacle located within 8 km of the estimated position of the aircraft.


CRUISING LEVELS

* Flight levels, for flights at or above the lowest usable flight level or, where applicable, above the transition altitude;
* Altitudes,   for   flights   below   the   lowest   usable   flight   level   or,   where   applicable, at or below the transition altitude

SIMULATED INSTRUMENT FLIGHTS

An aircraft shall not be flown under simulated instrument flight conditions unless:

* fully functioning dual controls are installed in the aircraft
* a qualified pilot occupies a control seat to act as safety pilot for the person who is flying under simulated instrument conditions. The safety pilot shall have  adequate  vision  forward  and  to  each  side  of  the  aircraft,  
* or  a  competent observer in communication with the safety pilot shall occupy a position in the aircraft from which the observer’s field of vision adequately supplements that of the safety pilot.

OPERATION IN VINCINITY OF AN AERODROME

aircraft on or in vincinity of an aerodrome shall - whether or not within the aerodrome traffic zone

* observe other aerodrome traffic for the purpose of avoiding collision;
* conform  with  or  avoid  the  pattern  of  traffic  formed  by  other  aircraft  in  operation;
* make all turns to the left, when approaching for a landing and after taking off, unless otherwise instructed; 
* land and take off into the wind unless safety, the runway configuration, or air traffic considerations determine that a different direction is preferable.


## Signals

* distress and urgency signals
* signals for use in event of an interception
* visual signals used to warn an unauthorised aircraft flying in, or about to enter a Restricted, Prohibited, or Danger Area
* signals for aerodrome traffic, and
* marshalling signals

### Distress Signals

The following signals - used either together or separately - mean that grave and imminent danger threatens and immediate assistance is requested:

* RT or other signalling method SOS ...---...
* RT spoken word MAYDAY
* distress message sent via data link transmitting intent of the word MAYDAY
* rockets or shells throwing red lights, fired one at a time at short intervals
* parachute flame showing red light

Art 41 ITU Radio Regulations: alarm signals for RT adn RT auto-alarms systems

* RT alarm signals consists of a series of 12 dashes sent in 1 minute, each dash 4 seconds, interval between consecutive dashes 1 second. Transmitted by hand, but automated instrument recommended.
* RT alarm signal consists of 2 substantially sinusoidal audio frequency tones transmitted alternately. One tone shave have frequence of 2.200 Hz and the other 1.300 Hz. Duration of each tone 250 miliseconds (0,25 seconds ~1/4 sec)
* RT alarm signal 
  + when generated automatically shall be sent continuously for a period of at least 30 seconds, but not exceeding 1 minutes
  + when generated by other means, the signal shall be sent as continously as practicable over a period of approximately 1 minute
  
### Urgency Signals

The following signals - used either together or separately - mean that an aircraft wishes to give notice of difficulties which compel it to land without requiring immediate assistance:

* repeated switching on and off of the landing lights; or
* repeated switching on and off of the navigatio lights in such a manner as to be distinct from flashing navigation lights.

The following signals - used either together or separately - mean that an aircraft has a very urgent message to transmit concerning the safety of a ship, aircraft, or other vehicle, or of some person on board or within sight:

* RT or other signalling method consisting of the group XXX ()
* RT urgency signal spoken word PAN-PAN
* urgency message sent via data link transmitting intent of the words PAN,PAN.

### Interception Signals

check table and put here.

### Warning Signals for unauthorised aircraft flying in, or about to enter a Restricted, Prohibited, or Danger Area

By day and night

* series of projectiles discharged from the ground at intervals of 10 seconds
* each showing - on bursting - red and green lights or stars

= aircraft in or about to enter Restricted, Prohibited, or Danger Area
= aircraft to take remedial action as may be necessary (i.e. leave/stay clear)

### Signals for Aerodrome Traffic

in flight

* pyrotechnic red - notwhithstanding any previous instruction, do not land for the time being
* steady red - (STOP) give way to other aircraft and continue circling
* green flashes - return for landing
* red flashes - aerodrome unsafe - do not land (hush away)
* white flashes - land at this aerodrome and proceed to apron
* steady green - (GO) cleared to land

on ground

* steady read - STOP (aka hold and give way)
* red flashes - (hush away) taxi clear of landing area in use
* green flashes - cleared to taxi
* white flashes - return to starting point on the aerodrome
* steady green - (GO) cleared for take-off

acknowledgement by aircraft

in flight

* during hours of daylight: rocking aircraft's wings (note: not on base and final legs)
* during hours of darkness: flashing on and off TWICE aircraft's landing lights or - if not so equipped - by switching on and off TWICE its navigation lights.

on ground

* during hours of daylight: moving aircraft's ailerons or rudder
* during hours of darkness: flashing on and off TWICE aircraft's landing lights or - if not so equipped - by switching on and off TWICE its navigation lights.

### Marshalling Signals

check for guide and add


## Air Traffic Control Service

### Clearances

An  air  traffic  control  clearance  shall  be  obtained  prior  to  operating  a  controlled  flight,  or  a  portion  of  a  flight  as  a  controlled  flight.  Such  clearance  shall  be  requested through the submission of a flight plan to an air traffic control unit.

Note  1  -  A  flight  plan  may  cover  only  part  of  a  flight,  as  necessary,  to  describe  that  portion  of  the  flight  or  those  manoeuvres  which  are  subject  to  air  traffic  control. A clearance may cover only part of a current flight plan, as indicated in a clearance limit or by reference to specific manoeuvres such as taxiing, landing or taking off.

Note 2- If an air traffic control clearance is not satisfactory to a pilot-in-command of an aircraft, the pilot-in command may request and, if practicable, will be issued an amended clearance

Priority

Whenever  an  aircraft  has  requested  a  clearance  involving  priority,  a  report  explaining  the  necessity  for  such  priority  shall  be  submitted, if  requested  by  the  appropriate air traffic control unit. Power driven heavier than air aircraft shall give way to airships, gliders and balloons.

Potential reclearance in flight

If prior to departure it is anticipated that depending on fuel endurance and subject to  reclearance  in  flight,  a  decision  may  be  taken  to  proceed  to  a  revised  destination aerodrome, the appropriate air traffic control units shall be so notified by  the  insertion  in  the  flight  plan  of  information  concerning  the  revised  route  (where known) and the revised destination.

An aircraft operated on a controlled aerodrome shall not taxi on the manoeuvring area  without  clearance  from  the  aerodrome  control  tower  and  shall  comply  with  any instructions given by that unit.

Termination of Control

A  controlled  flight  shall,  except  when  landing  at  a  controlled  aerodrome,  advise the  appropriate  ATC  unit  as  soon  as  it  ceases  to  be  subject  to  air  traffic  control  service

### Communications

to be continued.






BOOKDOWN EXAMPLE FOR ADDING CITATIONS   
You can write citations, too. For example, we are using the **bookdown** package [@R-bookdown] in this sample book, which was built on top of R Markdown and **knitr** [@xie2015].
